<Project>
    <PropertyGroup Condition="$(MSBuildProjectName) != 'GatheringPathRenderer'">
<!-- Version scheme: A.B.C.(D*100+E)
             A.B.C.D = upstream version from PunishXIV/Questionable
             E = downstream patch counter (01~99), reset per upstream release
             Current: upstream 15.306.3.18 + downstream 01 -->
        <Version>15.306.3.1804</Version>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);MSB3277;CA1506</NoWarn>
        <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277;CA1506</MSBuildWarningsAsMessages>
    </PropertyGroup>
</Project>
